name: quiz_app CICD

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Build the Docker image
      run: docker build . --tag ${{ secrets.DOCKER_USER }}/quiz_app:latest

    - name: Push to Docker Hub
      run: docker push ${{ secrets.DOCKER_USER }}/quiz_app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            sudo docker stop quiz_app
            sudo docker rm quiz_app
            sudo docker rmi ${{ secrets.DOCKER_USER }}/quiz_app
            sudo docker pull ${{ secrets.DOCKER_USER }}/quiz_app
            sudo docker run -d -p 80:3000 -t --restart always --name quiz_app ${{ secrets.DOCKER_USER }}/quiz_app:latest